[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["complex_mlp*", "simplemlp*", "utils*"]
exclude = ["tests*"]